#!/usr/bin/env bash
# HIGH-014 W8.02 — GCP IAM Discovery Script
# Purpose: Run on a machine with gcloud access to discover all SAs and IAM bindings,
#          then generate terraform import commands and populate iam.tf
#
# Usage:   chmod +x discover-iam.sh && ./discover-iam.sh
# Prereqs: gcloud auth (SA or user with roles/iam.securityReviewer)
# Output:  discover-results.json + import-iam.sh

set -euo pipefail

PROJECT="bdi-infrastructure"
OUT_DIR="$(dirname "$0")"
RESULTS="${OUT_DIR}/discover-results.json"
IMPORT_SCRIPT="${OUT_DIR}/import-iam.sh"

echo "═══════════════════════════════════════════════"
echo " HIGH-014 W8.02 GCP IAM Discovery"
echo " Project: ${PROJECT}"
echo " Date:    $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "═══════════════════════════════════════════════"

# ── Step 1: Discover Service Accounts ──
echo ""
echo "▶ Step 1/3: Listing service accounts..."
SA_LIST=$(gcloud iam service-accounts list --project="${PROJECT}" --format=json)
SA_COUNT=$(echo "${SA_LIST}" | jq length)
echo "  Found ${SA_COUNT} service accounts"

# ── Step 2: Discover IAM bindings on secrets ──
echo ""
echo "▶ Step 2/3: Listing IAM bindings on secrets..."

SECRETS=$(gcloud secrets list --project="${PROJECT}" --format="value(name)")
BINDINGS="[]"

for SECRET in ${SECRETS}; do
  POLICY=$(gcloud secrets get-iam-policy "${SECRET}" \
    --project="${PROJECT}" --format=json 2>/dev/null || echo '{"bindings":[]}')

  BINDING_COUNT=$(echo "${POLICY}" | jq '.bindings | length')
  if [ "${BINDING_COUNT}" -gt 0 ]; then
    ENRICHED=$(echo "${POLICY}" | jq --arg secret "${SECRET}" \
      '.bindings[] | {secret: $secret, role: .role, members: .members}')
    BINDINGS=$(echo "${BINDINGS}" | jq --argjson new "[${ENRICHED}]" '. + $new')
  fi
done

BIND_COUNT=$(echo "${BINDINGS}" | jq length)
echo "  Found ${BIND_COUNT} IAM bindings across secrets"

# ── Step 3: Discover project-level IAM ──
echo ""
echo "▶ Step 3/3: Listing project-level IAM policy..."
PROJECT_IAM=$(gcloud projects get-iam-policy "${PROJECT}" --format=json)

# ── Write results ──
echo ""
echo "▶ Writing results to ${RESULTS}..."
jq -n \
  --argjson service_accounts "${SA_LIST}" \
  --argjson secret_bindings "${BINDINGS}" \
  --argjson project_iam "${PROJECT_IAM}" \
  '{
    discovered_at: now | strftime("%Y-%m-%dT%H:%M:%SZ"),
    project: "'"${PROJECT}"'",
    service_accounts: $service_accounts,
    secret_iam_bindings: $secret_bindings,
    project_iam: $project_iam
  }' > "${RESULTS}"

# ── Generate import script ──
echo "▶ Generating ${IMPORT_SCRIPT}..."
cat > "${IMPORT_SCRIPT}" << 'HEADER'
#!/usr/bin/env bash
# AUTO-GENERATED by discover-iam.sh — terraform import commands for GCP IAM
set -euo pipefail
TF="terraform"
HEADER

echo "" >> "${IMPORT_SCRIPT}"
echo "# Service Accounts" >> "${IMPORT_SCRIPT}"
echo "${SA_LIST}" | jq -r '.[].email' | while read -r EMAIL; do
  SA_ID=$(echo "${EMAIL}" | cut -d@ -f1)
  RESOURCE_NAME=$(echo "${SA_ID}" | tr '-' '_')
  echo "\$TF import google_service_account.${RESOURCE_NAME} projects/${PROJECT}/serviceAccounts/${EMAIL}" >> "${IMPORT_SCRIPT}"
done

chmod +x "${IMPORT_SCRIPT}"

echo ""
echo "═══════════════════════════════════════════════"
echo " Discovery complete!"
echo " Results:  ${RESULTS}"
echo " Imports:  ${IMPORT_SCRIPT}"
echo ""
echo " Next steps:"
echo "   1. Review discover-results.json"
echo "   2. Add resource blocks to iam.tf"
echo "   3. Run import-iam.sh"
echo "   4. terraform plan (expect zero drift)"
echo "═══════════════════════════════════════════════"
